import play.sbt.routes.RoutesKeys
import sbt.Def
import scoverage.ScoverageKeys
import uk.gov.hmrc.versioning.SbtGitVersioning.autoImport.majorVersion

lazy val appName: String = "soft-drinks-industry-levy-returns-frontend"

ThisBuild / majorVersion := 0
ThisBuild / scalaVersion := "3.7.4"

lazy val root = (project in file("."))
  .enablePlugins(PlayScala, SbtDistributablesPlugin)
  .disablePlugins(JUnitXmlReportPlugin) // Required to prevent https://github.com/scalatest/scalatest/issues/1427
  .settings(inConfig(Test)(testSettings) *)
  .settings(
    libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
  ) // libraryDependencySchemes added to get around the scoverage compile errors for scala 2.13.10
  .settings(ThisBuild / useSuperShell := false)
  .settings(
    name := appName,
    RoutesKeys.routesImport ++= Seq(
      "models._",
      "uk.gov.hmrc.play.bootstrap.binders.RedirectUrl"
    ),
    TwirlKeys.templateImports ++= Seq(
      "play.twirl.api.HtmlFormat",
      "play.twirl.api.HtmlFormat._",
      "uk.gov.hmrc.govukfrontend.views.html.components._",
      "uk.gov.hmrc.hmrcfrontend.views.html.components._",
      "uk.gov.hmrc.hmrcfrontend.views.html.helpers._",
      "uk.gov.hmrc.hmrcfrontend.views.config._",
      "views.ViewUtils._",
      "models.Mode",
      "controllers.routes._",
      "viewmodels.govuk.all._"
    ),
    PlayKeys.playDefaultPort := 8703,
    coverageExcludedPackages := Seq(
      "<empty>",
      "uk.gov.hmrc.BuildInfo",
      "Reverse.*",
      ".*Routes.*",
      ".*RoutesPrefix.*",
      ".*GuiceInjector.*",
      "$anon",
      ".*handlers.*",
      ".*components.*",
      ".*repositories.*",
      ".*viewmodels.govuk.*"
    ).mkString(";"),
    coverageExcludedFiles := Seq(
      ".*EnrolmentStoreProxyConnector.*",
      ".*UserSearchConnector.*",
      ".*AdminController.*",
      ".*ActionHelpers.scala",
      ".*Actions.scala"
    ).mkString(";"),
    ScoverageKeys.coverageMinimumStmtTotal := 86,
    ScoverageKeys.coverageFailOnMinimum := true,
    ScoverageKeys.coverageHighlighting := true,
    scalacOptions ++= Seq(
      "-feature",
      "-Wconf:msg=Flag.*repeatedly:s",
      "-Wconf:msg=exhaustive*:s",
      "-Wconf:msg=unused explicit parameter*:s",
      "-Wconf:msg=unused private member*:s",
      "-Wconf:msg=unused implicit parameter*:s",
      "-Wconf:msg=unused local definition*:s",
      "-Wconf:msg=unused patterns*:s",
      "-Wconf:msg=unused import*:s"
    ),
    libraryDependencies ++= AppDependencies.all,
    retrieveManaged := true,
    // concatenate js
    Concat.groups := Seq(
      "javascripts/application.js" ->
        group(
          Seq(
            "javascripts/app.js"
          )
        )
    ),
    scalacOptions += "-deprecation",
    // prevent removal of unused code which generates warning errors due to use of third-party libs
    uglifyCompressOptions := Seq("unused=false", "dead_code=false"),
    pipelineStages := Seq(uglify),
    // below line required to force asset pipeline to operate in dev rather than only prod
    Assets / pipelineStages := Seq(concat, uglify),
    // only compress files generated by concat
    uglify / includeFilter := GlobFilter("application.js")
  )
  .settings(majorVersion := 0, libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always)
addCommandAlias("testAll", "; test ; it/test")

lazy val testSettings: Seq[Def.Setting[?]] = Seq(
  fork := true,
  unmanagedSourceDirectories += baseDirectory.value / "test-utils"
)

lazy val it = project
  .in(file("it"))
  .enablePlugins(PlayScala, ScoverageSbtPlugin)
  .dependsOn(root % "compile->compile,test;test->compile,test")
  .settings(
    name := s"$appName-it",
    libraryDependencies ++= AppDependencies.test,
    fork := true,
    // IMPORTANT: treat the it/ folder as the "test root"
    Test / unmanagedSourceDirectories := Seq(baseDirectory.value),
    Test / unmanagedResourceDirectories := Seq(baseDirectory.value / "resources")
  )
ThisBuild / scalacOptions ~= (_.distinct)